import { Nunito_Sans } from "next/font/google";
import "./globals.css";

import Nav from "./components/Nav";
import Footer from "./components/Footer";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <div id="modal"></div>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
